#!/usr/bin/env python3
"""
Resuelve los bloques SQL de un apunte: les aplica el resaltado del sitio y
reemplaza cada resultado por la salida real de la consulta.

    python herramientas/generar_apunte.py unidades/04-sql/apunte-sql.html

Qué toca de la página:

    <pre><code data-sql>SELECT ...</code></pre>   -> le pone los <span> del
                                                     resaltado
    <div data-resultado></div>                    -> lo llena con la tabla que
                                                     devuelve esa consulta

El ejemplo declara con qué juego de datos corre:

    <div class="ejemplo" data-base="base|ampliado"
         data-decimales="col_a,col_b"   (columnas que se muestran con 2 dec.)
         data-destacar="2"              (fila que se marca, base 0)
         data-sin-tabla="1">            (el ejemplo se corre, no se imprime)

Es idempotente: lee el SQL del propio HTML ya generado, así que la página
publicada es su propio original y se puede volver a correr cuantas veces haga
falta. Ninguna tabla de resultado se escribe a mano; si el modelo o los datos
cambian, se corre esto de nuevo y las salidas se acomodan solas.

La base sale de assets/consola/elchip.js, que genera mysql_a_postgres.py desde
ElChip.sql. Se arma en SQLite, en memoria: alcanza para el SQL de consulta de
este apunte y evita depender de un servidor instalado. Las consultas que usan
algo propio de MySQL se marcan con data-sin-tabla y se explican en el texto.
"""

import html
import json
import re
import sqlite3
import sys
import unicodedata
from pathlib import Path

RAIZ = Path(__file__).resolve().parents[1]

PALABRAS = r"""
    SELECT|FROM|WHERE|GROUP\s+BY|ORDER\s+BY|HAVING|LIMIT|OFFSET|AS|AND|OR|NOT|
    INNER\s+JOIN|LEFT\s+JOIN|RIGHT\s+JOIN|CROSS\s+JOIN|FULL\s+OUTER\s+JOIN|JOIN|ON|
    UNION\s+ALL|UNION|INSERT\s+INTO|VALUES|UPDATE|SET|DELETE|CREATE|ALTER|DROP|
    DISTINCT|BETWEEN|LIKE|IN|IS|NULL|EXISTS|ANY|SOME|ALL|CASE|WHEN|THEN|ELSE|END|
    WITH|RECURSIVE|ASC|DESC|COUNT|SUM|AVG|MIN|MAX|ROUND|COALESCE|IFNULL|
    GROUP_CONCAT|CONCAT|WITH\s+ROLLUP|ROLLUP|TRUE|FALSE
"""


# ---------------------------------------------------------------------------
# La base
# ---------------------------------------------------------------------------

def a_sqlite(sql: str) -> str:
    sql = re.sub(r"CREATE SCHEMA[^;]*;", "", sql, flags=re.I)
    sql = re.sub(r"SET search_path[^;]*;", "", sql, flags=re.I)
    sql = re.sub(r"INT GENERATED BY DEFAULT AS IDENTITY", "INTEGER", sql, flags=re.I)
    sql = re.sub(r"\bSERIAL\b", "INTEGER", sql, flags=re.I)
    sql = re.sub(r"\bTIMESTAMP\b", "TEXT", sql, flags=re.I)
    # Las columnas de texto se comparan y se ordenan como en MySQL. Sin esto,
    # un ORDER BY por nombre sale distinto: SQLite ordena por código de
    # carácter y pone «Samsung» antes que «iPhone».
    sql = re.sub(r"\bVARCHAR\(\d+\)", r"\g<0> COLLATE mysql_ai_ci", sql, flags=re.I)
    sql = re.sub(r"\bTEXT\b(?! COLLATE)", r"\g<0> COLLATE mysql_ai_ci", sql, flags=re.I)
    # de la vista en adelante hay funciones de Postgres que emulan IFNULL y
    # GROUP_CONCAT, y el bloque DO que reacomoda los contadores: SQLite no las
    # necesita
    for marca in ("CREATE VIEW", "DO $$"):
        corte = sql.upper().find(marca)
        if corte != -1:
            sql = sql[:corte]
    return sql


def plegar(texto: str) -> str:
    """Minúsculas y sin tildes, como compara MySQL con utf8mb4_0900_ai_ci."""
    sin_tilde = unicodedata.normalize("NFD", str(texto))
    sin_tilde = "".join(c for c in sin_tilde if unicodedata.category(c) != "Mn")
    return sin_tilde.casefold()


def concatenar(*partes):
    """CONCAT de MySQL: SQLite no lo tiene (usa ||), y devuelve NULL si alguna
    de las partes es NULL, igual que el motor."""
    if any(p is None for p in partes):
        return None
    return "".join(str(p) for p in partes)


def ordenar_como_mysql(a: str, b: str) -> int:
    """Ordena texto como MySQL: sin mirar mayúsculas ni tildes."""
    x, y = plegar(a), plegar(b)
    return (x > y) - (x < y)


def como(patron, valor, escape=None) -> bool:
    """El LIKE de MySQL, para SQLite.

    La base de El Chip es utf8mb4_0900_ai_ci: el LIKE de MySQL no distingue
    mayúsculas NI tildes, así que «bateria» encuentra «Batería». El de SQLite
    distingue las tildes, y sin esto las tablas del apunte saldrían con menos
    filas de las que ve el alumno en clase.
    """
    if patron is None or valor is None:
        return False
    regex = []
    for c in plegar(patron):
        if c == "%":
            regex.append(".*")
        elif c == "_":
            regex.append(".")
        else:
            regex.append(re.escape(c))
    return re.fullmatch("".join(regex), plegar(valor), re.S) is not None


def bases() -> dict[str, sqlite3.Connection]:
    js = (RAIZ / "assets" / "consola" / "elchip.js").read_text(encoding="utf-8")

    def const(nombre: str) -> str:
        ini = js.index("export const " + nombre)
        ini = js.index('"', ini)
        fin = js.index('";', ini)
        return a_sqlite(json.loads(js[ini:fin + 1]))

    esquema, datos, compendio = const("ESQUEMA"), const("DATOS_BASE"), const("DATOS_COMPENDIO")
    armadas = {}
    for nombre, partes in (("base", [esquema, datos]),
                           ("ampliado", [esquema, datos, compendio])):
        con = sqlite3.connect(":memory:")
        con.create_function("like", 2, como)
        con.create_function("like", 3, como)
        con.create_collation("mysql_ai_ci", ordenar_como_mysql)
        con.create_function("concat", -1, concatenar)
        con.execute("PRAGMA foreign_keys=ON")   # como InnoDB: las FK se respetan
        for parte in partes:
            con.executescript(parte)
        armadas[nombre] = con
    return armadas


# ---------------------------------------------------------------------------
# Resaltado
# ---------------------------------------------------------------------------

def texto_plano(fragmento: str) -> str:
    """Devuelve el SQL sin marcado, venga plano o ya resaltado."""
    return html.unescape(re.sub(r"<[^>]+>", "", fragmento))


def resaltar(sql: str) -> str:
    partes: list[str] = []

    patron = re.compile(
        r"(--[^\n]*)"                       # comentario
        r"|('(?:[^']|'')*')"                # cadena
        r"|(\b\d+(?:\.\d+)?\b)"             # número
        r"|(\b(?:" + PALABRAS + r")\b)",    # palabra clave
        re.I | re.X,
    )

    pos = 0
    for m in patron.finditer(sql):
        partes.append(html.escape(sql[pos:m.start()]))
        comentario, cadena, numero, palabra = m.groups()
        if comentario:
            partes.append(f'<span class="sql-comment">{html.escape(comentario)}</span>')
        elif cadena:
            partes.append(f'<span class="sql-string">{html.escape(cadena)}</span>')
        elif numero:
            partes.append(f'<span class="sql-number">{html.escape(numero)}</span>')
        else:
            partes.append(f'<span class="sql-keyword">{html.escape(palabra)}</span>')
        pos = m.end()
    partes.append(html.escape(sql[pos:]))
    return "".join(partes)


# ---------------------------------------------------------------------------
# Resultado
# ---------------------------------------------------------------------------

def celda(valor, columna: str, decimales: set[str]) -> str:
    if valor is None:
        return "NULL"
    if columna in decimales and isinstance(valor, (int, float)):
        return f"{valor:.2f}"
    if isinstance(valor, float):
        return f"{valor:g}"
    return str(valor)


def sentencias(sql: str) -> list[str]:
    """Parte el bloque en sentencias, sin cortar adentro de una cadena."""
    partes, actual, en_cadena = [], [], False
    for c in sql:
        if c == "'":
            en_cadena = not en_cadena
        if c == ";" and not en_cadena:
            partes.append("".join(actual))
            actual = []
        else:
            actual.append(c)
    partes.append("".join(actual))
    return [p.strip() for p in partes if p.strip()]


def formato_tabla(columnas: list[str], filas: list, decimales: set[str],
                  destacar: set[int]) -> str:
    """El HTML de una tabla de resultado. Lo comparten los dos motores, para
    que la página quede igual la arme quien la arme."""
    cabeza = "".join(f"<th>{html.escape(c)}</th>" for c in columnas)
    cuerpo = []
    for i, fila in enumerate(filas):
        celdas = "".join(
            f"<td>{html.escape(celda(v, columnas[j], decimales))}</td>"
            for j, v in enumerate(fila)
        )
        clase = ' class="destacada"' if i in destacar else ""
        cuerpo.append(f"<tr{clase}>{celdas}</tr>")

    plural = "fila" if len(filas) == 1 else "filas"
    return (
        '<div class="table-scroll">\n'
        '            <table class="result-table">\n'
        f'              <thead><tr>{cabeza}</tr></thead>\n'
        "              <tbody>\n"
        + "".join(f"                {f}\n" for f in cuerpo)
        + "              </tbody>\n"
        "            </table>\n"
        "          </div>\n"
        f'          <p class="filas-devueltas">{len(filas)} {plural}</p>'
    )


def tabla(con: sqlite3.Connection, sql: str, decimales: set[str], destacar: set[int]) -> str:
    # Un ejemplo puede traer un UPDATE o un DELETE y después el SELECT que
    # muestra el efecto. Todo corre dentro de una transacción que se deshace:
    # así el ejemplo se ve, y los ejemplos que siguen encuentran la base como
    # estaba. El resultado que se publica es el de la última sentencia que
    # devuelve filas.
    cur = None
    con.execute("BEGIN")
    try:
        for sentencia in sentencias(sql):
            paso = con.execute(sentencia)
            if paso.description:
                cur = paso
                filas_ultimas = paso.fetchall()
        if cur is None:
            raise sqlite3.Error("el ejemplo no termina en una consulta que devuelva filas")
        columnas = [d[0] for d in cur.description]
        filas = filas_ultimas
    finally:
        con.rollback()

    return formato_tabla(columnas, filas, decimales, destacar)


# ---------------------------------------------------------------------------
# Recorrido de la página
# ---------------------------------------------------------------------------

def cierre_del_div(txt: str, desde: int) -> int:
    """Posición del </div> que cierra el <div ...> que empieza en `desde`."""
    i = txt.index(">", desde) + 1
    prof = 1
    for m in re.finditer(r"<(/?)div\b[^>]*>", txt[i:]):
        prof += -1 if m.group(1) else 1
        if prof == 0:
            return i + m.start()
    raise ValueError("un <div> quedó sin cerrar")


def procesar(ruta: Path) -> tuple[int, int]:
    txt = ruta.read_text(encoding="utf-8")
    conexiones = bases()
    codigos = resultados = 0

    # 1. los bloques de código, uno por uno
    def rehacer_codigo(m: re.Match) -> str:
        nonlocal codigos
        codigos += 1
        return m.group(1) + resaltar(texto_plano(m.group(2))) + m.group(3)

    txt = re.sub(r"(<code data-sql>)(.*?)(</code>)", rehacer_codigo, txt, flags=re.S)

    # 2. los resultados, dentro de cada ejemplo
    salida = []
    pos = 0
    for m in re.finditer(r'<div class="ejemplo"([^>]*)>', txt):
        atributos = m.group(1)
        fin = cierre_del_div(txt, m.start())
        bloque = txt[m.start():fin]

        hueco = re.search(r"<div data-resultado>", bloque)
        if not hueco or "data-sin-tabla" in atributos:
            continue

        # Hay comportamientos que SQLite no reproduce —el contador de
        # AUTO_INCREMENT, que en MySQL no vuelve atrás después de un DELETE y
        # en SQLite sí reutiliza el número—. Esos ejemplos se marcan con
        # data-motor="mysql" y su tabla la escribe verificar_apunte_mysql.py.
        if 'data-motor="mysql"' in atributos:
            continue

        codigo = re.search(r"<code data-sql>(.*?)</code>", bloque, re.S)
        if not codigo:
            print(f"  SIN SQL  un ejemplo pide resultado y no tiene consulta")
            continue

        cual = (re.search(r'data-base="(\w+)"', atributos) or [None, "base"])[1]
        dec = (re.search(r'data-decimales="([^"]*)"', atributos) or [None, ""])[1]
        des = (re.search(r'data-destacar="([^"]*)"', atributos) or [None, ""])[1]
        decimales = {c.strip() for c in dec.split(",") if c.strip()}
        destacar = {int(n) for n in des.split(",") if n.strip().isdigit()}

        sql = texto_plano(codigo.group(1)).strip()
        try:
            contenido = tabla(conexiones[cual], sql, decimales, destacar)
        except sqlite3.Error as e:
            print(f"  ERROR    {e}\n           en: {sql.splitlines()[0]}…")
            continue

        ini_h = m.start() + hueco.start()
        fin_h = cierre_del_div(txt, ini_h)
        salida.append(txt[pos:ini_h])
        salida.append(f"<div data-resultado>{contenido}</div>")
        pos = fin_h + len("</div>")
        resultados += 1

    salida.append(txt[pos:])
    ruta.write_text("".join(salida), encoding="utf-8")
    return codigos, resultados


def main() -> None:
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    for nombre in sys.argv[1:]:
        ruta = Path(nombre)
        if not ruta.is_absolute():
            ruta = RAIZ / nombre
        codigos, resultados = procesar(ruta)
        print(f"{ruta.name}: {codigos} bloques de SQL, {resultados} resultados")


if __name__ == "__main__":
    main()
