-- MySQL Script generated by MySQL Workbench
-- Mon Jun  1 08:18:26 2026
-- Model: New Model    Version: 1.5
-- Refactored: Added Marca, EmailTipo, and Email tables. 
--             Restored Cliente-Telefono relationships.
--             Implemented N:M for Pagos.
--             Fixed View Syntax.

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema el_chip
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `el_chip` ;
CREATE SCHEMA IF NOT EXISTS `el_chip` ;
USE `el_chip` ;

-- -----------------------------------------------------
-- 1. TABLAS MAESTRAS (Sin dependencias / FKs)
-- -----------------------------------------------------

-- Table `el_chip`.`rol`
CREATE TABLE IF NOT EXISTS `el_chip`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;

-- Table `el_chip`.`orden_estado`
CREATE TABLE IF NOT EXISTS `el_chip`.`orden_estado` (
  `id_orden_estado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_orden_estado`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;

-- Table `el_chip`.`metodo_pago`
CREATE TABLE IF NOT EXISTS `el_chip`.`metodo_pago` (
  `id_metodo_pago` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_metodo_pago`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;

-- Table `el_chip`.`telefonotipo`
CREATE TABLE IF NOT EXISTS `el_chip`.`telefonotipo` (
  `id_telefonotipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_telefonotipo`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;

-- Table `el_chip`.`direcciontipo`
CREATE TABLE IF NOT EXISTS `el_chip`.`direcciontipo` (
  `id_direcciontipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_direcciontipo`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;

-- Table `el_chip`.`emailtipo`
CREATE TABLE IF NOT EXISTS `el_chip`.`emailtipo` (
  `id_emailtipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NULL,
  PRIMARY KEY (`id_emailtipo`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE)
ENGINE = InnoDB;

-- Table `el_chip`.`marca`
CREATE TABLE IF NOT EXISTS `el_chip`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_marca`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;

-- Table `el_chip`.`problema`
CREATE TABLE IF NOT EXISTS `el_chip`.`problema` (
  `id_problema` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(255) NOT NULL,
  `mano_obra` DECIMAL(12,2) NULL,
  PRIMARY KEY (`id_problema`))
ENGINE = InnoDB;

-- Table `el_chip`.`repuesto`
CREATE TABLE IF NOT EXISTS `el_chip`.`repuesto` (
  `id_repuesto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `stock` INT NULL DEFAULT 0,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_repuesto`))
ENGINE = InnoDB;

-- Table `el_chip`.`cliente`
CREATE TABLE IF NOT EXISTS `el_chip`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;

-- Table `el_chip`.`equipo`
CREATE TABLE IF NOT EXISTS `el_chip`.`equipo` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `id_marca` INT NOT NULL,
  `modelo` VARCHAR(100) NULL DEFAULT NULL,
  `nro_serie` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_equipo`),
  UNIQUE INDEX `nro_serie_UNIQUE` (`nro_serie` ASC) VISIBLE,
  INDEX `fk_equipo_marca_idx` (`id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_equipo_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `el_chip`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 2. TABLAS CON DEPENDENCIAS (Foreign Keys)
-- -----------------------------------------------------

-- Table `el_chip`.`empleado`
CREATE TABLE IF NOT EXISTS `el_chip`.`empleado` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX (`usuario` ASC) VISIBLE,
  INDEX `fk_empleado_rol_idx` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `el_chip`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `el_chip`.`orden_servicio`
CREATE TABLE IF NOT EXISTS `el_chip`.`orden_servicio` (
  `nro_orden` INT NOT NULL AUTO_INCREMENT,
  `fecha_ingreso` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_entrega` DATETIME NULL DEFAULT NULL,
  `descuento` DECIMAL(5,2) NULL DEFAULT 0.00,
  `total` DECIMAL(10,2) NULL DEFAULT 0.00,
  `id_empleado` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  `id_orden_estado` INT NOT NULL,
  PRIMARY KEY (`nro_orden`),
  INDEX `fk_orden_servicio_empleado_idx` (`id_empleado` ASC) VISIBLE,
  INDEX `fk_orden_servicio_cliente_idx` (`id_cliente` ASC) VISIBLE,
  INDEX `fk_orden_servicio_estado_idx` (`id_orden_estado` ASC) VISIBLE,
  CONSTRAINT `fk_orden_servicio_empleado`
    FOREIGN KEY (`id_empleado`)
    REFERENCES `el_chip`.`empleado` (`id_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_servicio_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `el_chip`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_servicio_estado`
    FOREIGN KEY (`id_orden_estado`)
    REFERENCES `el_chip`.`orden_estado` (`id_orden_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `el_chip`.`orden_servicio_pago`
CREATE TABLE IF NOT EXISTS `el_chip`.`orden_servicio_pago` (
  `nro_orden` INT NOT NULL,
  `id_metodo_pago` INT NOT NULL,
  `monto` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `fecha_pago` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`nro_orden`, `id_metodo_pago`),
  INDEX `fk_osp_metodo_pago_idx` (`id_metodo_pago` ASC) VISIBLE,
  INDEX `fk_osp_orden_idx` (`nro_orden` ASC) VISIBLE,
  CONSTRAINT `fk_osp_orden`
    FOREIGN KEY (`nro_orden`)
    REFERENCES `el_chip`.`orden_servicio` (`nro_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_osp_metodo_pago`
    FOREIGN KEY (`id_metodo_pago`)
    REFERENCES `el_chip`.`metodo_pago` (`id_metodo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `el_chip`.`telefono`
CREATE TABLE IF NOT EXISTS `el_chip`.`telefono` (
  `id_telefono` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(14) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `id_telefonotipo` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_telefono`),
  INDEX `fk_telefono_tipo_idx` (`id_telefonotipo` ASC) VISIBLE,
  INDEX `fk_telefono_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_telefono_tipo`
    FOREIGN KEY (`id_telefonotipo`)
    REFERENCES `el_chip`.`telefonotipo` (`id_telefonotipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_telefono_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `el_chip`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `el_chip`.`email`
CREATE TABLE IF NOT EXISTS `el_chip`.`email` (
  `id_email` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `id_emailtipo` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_email`),
  INDEX `fk_email_tipo_idx` (`id_emailtipo` ASC) VISIBLE,
  INDEX `fk_email_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_email_tipo`
    FOREIGN KEY (`id_emailtipo`)
    REFERENCES `el_chip`.`emailtipo` (`id_emailtipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_email_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `el_chip`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `el_chip`.`direccion`
CREATE TABLE IF NOT EXISTS `el_chip`.`direccion` (
  `id_direccion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `id_direcciontipo` INT NOT NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `fk_direccion_tipo_idx` (`id_direcciontipo` ASC) VISIBLE,
  INDEX `fk_direccion_cliente_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_tipo`
    FOREIGN KEY (`id_direcciontipo`)
    REFERENCES `el_chip`.`direcciontipo` (`id_direcciontipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `el_chip`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `el_chip`.`orden_servicio_has_equipo`
CREATE TABLE IF NOT EXISTS `el_chip`.`orden_servicio_has_equipo` (
  `nro_orden` INT NOT NULL,
  `id_equipo` INT NOT NULL,
  `id_problema` INT NOT NULL,
  PRIMARY KEY (`nro_orden`, `id_equipo`, `id_problema`),
  INDEX `fk_ose_equipo_idx` (`id_equipo` ASC) VISIBLE,
  INDEX `fk_ose_orden_idx` (`nro_orden` ASC) VISIBLE,
  INDEX `fk_ose_problema_idx` (`id_problema` ASC) VISIBLE,
  CONSTRAINT `fk_ose_orden`
    FOREIGN KEY (`nro_orden`)
    REFERENCES `el_chip`.`orden_servicio` (`nro_orden`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ose_equipo`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `el_chip`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ose_problema`
    FOREIGN KEY (`id_problema`)
    REFERENCES `el_chip`.`problema` (`id_problema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Table `el_chip`.`problema_has_repuesto`
CREATE TABLE IF NOT EXISTS `el_chip`.`problema_has_repuesto` (
  `id_problema` INT NOT NULL,
  `id_repuesto` INT NOT NULL,
  `cantidad` INT NOT NULL DEFAULT 1,
  `precio_unitario` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `mano_obra` DECIMAL(12,2) NULL,
  PRIMARY KEY (`id_problema`, `id_repuesto`),
  INDEX `fk_phr_repuesto_idx` (`id_repuesto` ASC) VISIBLE,
  INDEX `fk_phr_problema_idx` (`id_problema` ASC) VISIBLE,
  CONSTRAINT `fk_phr_problema`
    FOREIGN KEY (`id_problema`)
    REFERENCES `el_chip`.`problema` (`id_problema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_phr_repuesto`
    FOREIGN KEY (`id_repuesto`)
    REFERENCES `el_chip`.`repuesto` (`id_repuesto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- 3. VISTAS
-- -----------------------------------------------------

USE `el_chip`;
DROP VIEW IF EXISTS `orden_servicio_completa`;

CREATE VIEW `orden_servicio_completa` AS
SELECT
	O.nro_orden AS 'Nro Orden',
	CONCAT(C.apellido, ', ', C.nombre) AS 'Cliente',
	GROUP_CONCAT(DISTINCT M.nombre SEPARATOR ' / ') AS 'Marcas',
	GROUP_CONCAT(DISTINCT E.modelo SEPARATOR ' / ') AS 'Modelos',
	GROUP_CONCAT(DISTINCT P.descripcion SEPARATOR ' + ') AS 'Problemas Detectados',
	O.fecha_ingreso AS 'Fecha Ingreso',
	ST.nombre AS 'Estado Actual',
	GROUP_CONCAT(DISTINCT MP.nombre SEPARATOR ' + ') AS 'Metodos de Pago',
	O.total AS 'Monto Total'
FROM `orden_servicio` AS O
INNER JOIN `cliente` AS C ON C.id_cliente = O.id_cliente
INNER JOIN `orden_servicio_has_equipo` AS OSE ON OSE.nro_orden = O.nro_orden
INNER JOIN `equipo` AS E ON E.id_equipo = OSE.id_equipo
INNER JOIN `marca` AS M ON M.id_marca = E.id_marca
INNER JOIN `problema` AS P ON P.id_problema = OSE.id_problema
INNER JOIN `orden_estado` AS ST ON ST.id_orden_estado = O.id_orden_estado
LEFT JOIN `orden_servicio_pago` AS OSP ON OSP.nro_orden = O.nro_orden
LEFT JOIN `metodo_pago` AS MP ON MP.id_metodo_pago = OSP.id_metodo_pago
GROUP BY O.nro_orden;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
